use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct HotKeyConfig {
    pub auto_track_hotkey: String,
    pub auto_track_hotkey_type: String,
    pub auto_domain_hotkey: String,
    pub auto_domain_hotkey_type: String,
    pub auto_fight_hotkey: String,
    pub auto_fight_hotkey_type: String,
    pub auto_fishing_enabled_hotkey: String,
    pub auto_fishing_enabled_hotkey_type: String,
    pub auto_genius_invokation_hotkey: String,
    pub auto_genius_invokation_hotkey_type: String,
    pub bgi_enabled_hotkey: String,
    pub bgi_enabled_hotkey_type: String,
    pub auto_pick_enabled_hotkey: String,
    pub auto_pick_enabled_hotkey_type: String,
    pub auto_skip_enabled_hotkey: String,
    pub auto_skip_enabled_hotkey_type: String,
    pub auto_skip_hangout_enabled_hotkey: String,
    pub auto_skip_hangout_enabled_hotkey_type: String,
    pub auto_wood_hotkey: String,
    pub auto_wood_hotkey_type: String,
    pub enhance_artifact_hotkey: String,
    pub enhance_artifact_hotkey_type: String,
    pub quick_buy_hotkey: String,
    pub quick_buy_hotkey_type: String,
    pub quick_serenitea_pot_hotkey: String,
    pub quick_serenitea_pot_hotkey_type: String,
    pub quick_teleport_enabled_hotkey: String,
    pub quick_teleport_enabled_hotkey_type: String,
    pub quick_teleport_tick_hotkey: String,
    pub quick_teleport_tick_hotkey_type: String,
    pub skill_cd_enabled_hotkey: String,
    pub skill_cd_enabled_hotkey_type: String,
    pub take_screenshot_hotkey: String,
    pub take_screenshot_hotkey_type: String,
    pub turn_around_hotkey: String,
    pub turn_around_hotkey_type: String,
    pub click_genshin_confirm_button_hotkey: String,
    pub click_genshin_confirm_button_hotkey_type: String,
    pub click_genshin_cancel_button_hotkey: String,
    pub click_genshin_cancel_button_hotkey_type: String,
    pub one_key_fight_hotkey: String,
    pub one_key_fight_hotkey_type: String,
    pub map_pos_record_hotkey: String,
    pub map_pos_record_hotkey_type: String,
    pub auto_music_game_hotkey: String,
    pub auto_music_game_hotkey_type: String,
    pub auto_fishing_game_hotkey: String,
    pub auto_fishing_game_hotkey_type: String,
    pub auto_cook_game_hotkey: String,
    pub auto_cook_game_hotkey_type: String,
    pub auto_track_path_hotkey: String,
    pub auto_track_path_hotkey_type: String,
    pub test1_hotkey: String,
    pub test1_hotkey_type: String,
    pub test2_hotkey: String,
    pub test2_hotkey_type: String,
    pub rec_big_map_pos_hotkey: String,
    pub rec_big_map_pos_hotkey_type: String,
    pub path_recorder_hotkey: String,
    pub path_recorder_hotkey_type: String,
    pub add_waypoint_hotkey: String,
    pub add_waypoint_hotkey_type: String,
    pub execute_path_hotkey: String,
    pub execute_path_hotkey_type: String,
    pub log_box_display_hotkey: String,
    pub log_box_display_hotkey_type: String,
    pub key_mouse_macro_record_hotkey: String,
    pub key_mouse_macro_record_hotkey_type: String,
    pub suspend_hotkey: String,
    pub suspend_hotkey_type: String,
    pub cancel_task_hotkey: String,
    pub cancel_task_hotkey_type: String,
    pub onedragon_hotkey: String,
    pub onedragon_hotkey_type: String,
    pub map_mask_enabled_hotkey: String,
    pub map_mask_enabled_hotkey_type: String,
    #[serde(flatten)]
    pub extra: Map<String, Value>,
}

impl Default for HotKeyConfig {
    fn default() -> Self {
        const KEYBOARD_MONITOR: &str = "KeyboardMonitor";
        Self {
            auto_track_hotkey: String::new(),
            auto_track_hotkey_type: KEYBOARD_MONITOR.to_string(),
            auto_domain_hotkey: String::new(),
            auto_domain_hotkey_type: KEYBOARD_MONITOR.to_string(),
            auto_fight_hotkey: String::new(),
            auto_fight_hotkey_type: KEYBOARD_MONITOR.to_string(),
            auto_fishing_enabled_hotkey: String::new(),
            auto_fishing_enabled_hotkey_type: KEYBOARD_MONITOR.to_string(),
            auto_genius_invokation_hotkey: String::new(),
            auto_genius_invokation_hotkey_type: KEYBOARD_MONITOR.to_string(),
            bgi_enabled_hotkey: "F11".to_string(),
            bgi_enabled_hotkey_type: "GlobalRegister".to_string(),
            auto_pick_enabled_hotkey: String::new(),
            auto_pick_enabled_hotkey_type: KEYBOARD_MONITOR.to_string(),
            auto_skip_enabled_hotkey: String::new(),
            auto_skip_enabled_hotkey_type: KEYBOARD_MONITOR.to_string(),
            auto_skip_hangout_enabled_hotkey: String::new(),
            auto_skip_hangout_enabled_hotkey_type: KEYBOARD_MONITOR.to_string(),
            auto_wood_hotkey: String::new(),
            auto_wood_hotkey_type: KEYBOARD_MONITOR.to_string(),
            enhance_artifact_hotkey: String::new(),
            enhance_artifact_hotkey_type: KEYBOARD_MONITOR.to_string(),
            quick_buy_hotkey: String::new(),
            quick_buy_hotkey_type: KEYBOARD_MONITOR.to_string(),
            quick_serenitea_pot_hotkey: String::new(),
            quick_serenitea_pot_hotkey_type: KEYBOARD_MONITOR.to_string(),
            quick_teleport_enabled_hotkey: String::new(),
            quick_teleport_enabled_hotkey_type: KEYBOARD_MONITOR.to_string(),
            quick_teleport_tick_hotkey: String::new(),
            quick_teleport_tick_hotkey_type: KEYBOARD_MONITOR.to_string(),
            skill_cd_enabled_hotkey: String::new(),
            skill_cd_enabled_hotkey_type: KEYBOARD_MONITOR.to_string(),
            take_screenshot_hotkey: String::new(),
            take_screenshot_hotkey_type: KEYBOARD_MONITOR.to_string(),
            turn_around_hotkey: String::new(),
            turn_around_hotkey_type: KEYBOARD_MONITOR.to_string(),
            click_genshin_confirm_button_hotkey: String::new(),
            click_genshin_confirm_button_hotkey_type: KEYBOARD_MONITOR.to_string(),
            click_genshin_cancel_button_hotkey: String::new(),
            click_genshin_cancel_button_hotkey_type: KEYBOARD_MONITOR.to_string(),
            one_key_fight_hotkey: String::new(),
            one_key_fight_hotkey_type: KEYBOARD_MONITOR.to_string(),
            map_pos_record_hotkey: String::new(),
            map_pos_record_hotkey_type: KEYBOARD_MONITOR.to_string(),
            auto_music_game_hotkey: String::new(),
            auto_music_game_hotkey_type: KEYBOARD_MONITOR.to_string(),
            auto_fishing_game_hotkey: String::new(),
            auto_fishing_game_hotkey_type: KEYBOARD_MONITOR.to_string(),
            auto_cook_game_hotkey: String::new(),
            auto_cook_game_hotkey_type: KEYBOARD_MONITOR.to_string(),
            auto_track_path_hotkey: String::new(),
            auto_track_path_hotkey_type: KEYBOARD_MONITOR.to_string(),
            test1_hotkey: String::new(),
            test1_hotkey_type: KEYBOARD_MONITOR.to_string(),
            test2_hotkey: String::new(),
            test2_hotkey_type: KEYBOARD_MONITOR.to_string(),
            rec_big_map_pos_hotkey: String::new(),
            rec_big_map_pos_hotkey_type: KEYBOARD_MONITOR.to_string(),
            path_recorder_hotkey: String::new(),
            path_recorder_hotkey_type: KEYBOARD_MONITOR.to_string(),
            add_waypoint_hotkey: String::new(),
            add_waypoint_hotkey_type: KEYBOARD_MONITOR.to_string(),
            execute_path_hotkey: String::new(),
            execute_path_hotkey_type: KEYBOARD_MONITOR.to_string(),
            log_box_display_hotkey: String::new(),
            log_box_display_hotkey_type: KEYBOARD_MONITOR.to_string(),
            key_mouse_macro_record_hotkey: String::new(),
            key_mouse_macro_record_hotkey_type: KEYBOARD_MONITOR.to_string(),
            suspend_hotkey: String::new(),
            suspend_hotkey_type: KEYBOARD_MONITOR.to_string(),
            cancel_task_hotkey: String::new(),
            cancel_task_hotkey_type: KEYBOARD_MONITOR.to_string(),
            onedragon_hotkey: String::new(),
            onedragon_hotkey_type: KEYBOARD_MONITOR.to_string(),
            map_mask_enabled_hotkey: String::new(),
            map_mask_enabled_hotkey_type: KEYBOARD_MONITOR.to_string(),
            extra: Map::new(),
        }
    }
}
