use super::{TaskCatalogEntry, TaskKind, TaskLaunchPolicy, TaskPortState};

static TASK_CATALOG: &[TaskCatalogEntry] = &[
    TaskCatalogEntry {
        key: "RecognitionTest",
        display_name: "Recognition Test",
        kind: TaskKind::RealtimeTrigger,
        legacy_type: "BetterGenshinImpact.GameTask.Placeholder.TestTrigger",
        legacy_reference: "BetterGenshinImpact/GameTask/Placeholder/PlaceholderTrigger.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &[],
        launch_policy: TaskLaunchPolicy::RealtimeTick,
        requires_main_ui_wait: None,
        port_state: TaskPortState::MetadataOnly,
        notes: "Developer placeholder trigger loaded first by GameTaskManager.",
    },
    TaskCatalogEntry {
        key: "GameLoading",
        display_name: "Game Loading",
        kind: TaskKind::RealtimeTrigger,
        legacy_type: "BetterGenshinImpact.GameTask.GameLoading.GameLoadingTrigger",
        legacy_reference: "BetterGenshinImpact/GameTask/GameLoading/GameLoading.cs",
        config_section: Some("genshinStartConfig"),
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/GameLoading/Assets",
            "GameTask/Common/Element/Assets",
        ],
        launch_policy: TaskLaunchPolicy::RealtimeTick,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models auto-enter gating, template/OCR locators, Bilibili login windows, Starward playtime plan, server-resolution rules, and an injectable tick executor; desktop capture/input/config.ini/registry/protocol adapters remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoPick",
        display_name: "Auto Pick",
        kind: TaskKind::RealtimeTrigger,
        legacy_type: "BetterGenshinImpact.GameTask.AutoPick.AutoPickTrigger",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoPick/AutoPickTrigger.cs",
        config_section: Some("autoPickConfig"),
        hotkey_fields: &["autoPickEnabledHotkey"],
        asset_roots: &[
            "GameTask/AutoPick/Assets",
            "GameTask/AutoSkip/Assets",
            "Assets/Config/Pick",
        ],
        launch_policy: TaskLaunchPolicy::RealtimeTick,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust has config, trigger descriptor, asset resolution, OCR text cleanup, pure black/white-list logic, pure tick decision reports, and an injectable tick executor for key/scroll/wait actions; desktop AutoPick tick now wires BitBlt capture, F/L/chat/settings PureRust template matching, scroll icon color probing, runner pause-count gate, black/white list file loading, SendInput pick-key dispatch, mouse-wheel scroll, and delay handling, while Sobel/morphology text extraction and Paddle/Yap OCR remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoEat",
        display_name: "Auto Eat",
        kind: TaskKind::RealtimeTrigger,
        legacy_type: "BetterGenshinImpact.GameTask.AutoEat.AutoEatTrigger",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoEat/AutoEatTrigger.cs",
        config_section: Some("autoEatConfig"),
        hotkey_fields: &[],
        asset_roots: &["GameTask/AutoEat/Assets"],
        launch_policy: TaskLaunchPolicy::RealtimeTick,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models low-HP recovery, resurrection icon locators, timing/cache rules, pure trigger tick decision, injectable tick executor, and QuickUseGadget action dispatch plan; desktop AutoEat tick now wires BitBlt capture, low-HP pixel probing, Recovery/Resurrection template matching, foreground-window preflight, and SendInput QuickUseGadget dispatch; script-dispatched solo food-inventory flow is tracked by AutoEatFood, while full BV current-avatar parity and notifications remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoEatFood",
        display_name: "Auto Eat Food",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoEat.AutoEatTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoEat/AutoEatTask.cs",
        config_section: Some("autoEatConfig"),
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/AutoEat/Assets",
            "GameTask/Common/Element/Assets",
            "Assets/Model/Item",
        ],
        launch_policy: TaskLaunchPolicy::ScriptDispatcher,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models script-dispatched AutoEat foodName/foodEffectType resolution, default buff-food skip semantics, Food inventory grid/classifier/OCR rules through CountInventoryItem, use-confirm contract, full-width digit normalization, legacy int? return values, explicit scan_complete protection, shared script-dispatcher/independent-task plan routing, and an injectable inventory-food executor; desktop script-dispatcher live execution now covers the missing-default and portable-bag skip/no-op branches and runs inventory-food through shared game-window, BitBlt, capture-size, inventory open/prompt/tab handling, first-page de-highlight/column stitching, stitched visible-cell crop caching, and GridIcon classifier asset preflight before the live GridIcon ONNX/OCR/click adapters are wired.",
    },
    TaskCatalogEntry {
        key: "QuickTeleport",
        display_name: "Quick Teleport",
        kind: TaskKind::RealtimeTrigger,
        legacy_type: "BetterGenshinImpact.GameTask.QuickTeleport.QuickTeleportTrigger",
        legacy_reference: "BetterGenshinImpact/GameTask/QuickTeleport/QuickTeleportTrigger.cs",
        config_section: Some("quickTeleportConfig"),
        hotkey_fields: &["quickTeleportEnabledHotkey", "quickTeleportTickHotkey"],
        asset_roots: &["GameTask/QuickTeleport/Assets"],
        launch_policy: TaskLaunchPolicy::RealtimeTick,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models config, BigMap trigger metadata, teleport/list template locators, HDR-aware OCR rules, pure tick/candidate decision ordering, injectable tick executor, and tick plan; desktop QuickTeleport tick now wires BitBlt capture, PureRust BigMap/teleport/close/map-choose template matching, map-choose icon probing with candidate de-duplication, WinRT candidate-text OCR with standard white-text filtering, foreground-aware legacy hold-hotkey polling, tick-local Chat UI hotkey latch suppression, persistent throttle state, SendInput teleport-button/candidate clicks, and fresh teleport-button recheck, while HDR capture-path parity, native global hook event-source parity, real-game OCR regression, and full Teleport/TpTask map navigation remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoSkip",
        display_name: "Auto Skip",
        kind: TaskKind::RealtimeTrigger,
        legacy_type: "BetterGenshinImpact.GameTask.AutoSkip.AutoSkipTrigger",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoSkip/AutoSkipTrigger.cs",
        config_section: Some("autoSkipConfig"),
        hotkey_fields: &["autoSkipEnabledHotkey", "autoSkipHangoutEnabledHotkey"],
        asset_roots: &[
            "GameTask/AutoSkip/Assets",
            "GameTask/AutoPick/Assets",
            "GameTask/Common/Element/Assets",
            "Assets/Config/Skip",
        ],
        launch_policy: TaskLaunchPolicy::RealtimeTick,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models background-capable dialog trigger metadata, config, assets, option/audio/black-screen/hangout/submit-goods rules, pure dialogue/hangout option decisions, and an injectable tick executor covering audio wait, daily rewards, popup cleanup, key-based option selection, expedition, hangout, black-screen, and foreground restore actions; live OCR, audio, input, window, and expedition adapters remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoFish",
        display_name: "Auto Fishing Trigger",
        kind: TaskKind::RealtimeTrigger,
        legacy_type: "BetterGenshinImpact.GameTask.AutoFishing.AutoFishingTrigger",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoFishing/AutoFishingTrigger.cs",
        config_section: Some("autoFishingConfig"),
        hotkey_fields: &["autoFishingEnabledHotkey", "autoFishingGameHotkey"],
        asset_roots: &["GameTask/AutoFishing/Assets"],
        launch_policy: TaskLaunchPolicy::RealtimeTick,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models AutoFish realtime trigger metadata, config, AutoFishing templates, exclusive fishing UI gate, semi-auto behavior tree, bite detection, fish-bar contour rules, trigger state, and an injectable tick executor for bite/bar/input/overlay actions; desktop live phase 1 now wires BitBlt capture, fishing UI/lift-rod template matching, SendInput left-button actions, persistent trigger state, and no-op overlay cleanup, while white text block detection, Paddle OCR, fish-box/fishing-bar contour adapters, and full AutoFishingTask throw-rod execution remain pending.",
    },
    TaskCatalogEntry {
        key: "SkillCd",
        display_name: "Skill Cooldown",
        kind: TaskKind::RealtimeTrigger,
        legacy_type: "BetterGenshinImpact.GameTask.SkillCd.SkillCdTrigger",
        legacy_reference: "BetterGenshinImpact/GameTask/SkillCd/SkillCdTrigger.cs",
        config_section: Some("skillCdConfig"),
        hotkey_fields: &["skillCdEnabledHotkey"],
        asset_roots: &["GameTask/AutoFight/Assets"],
        launch_policy: TaskLaunchPolicy::RealtimeTick,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models SkillCd config clamps, Main/Domain gating, team sync delays, key-state rules, OCR parsing/fallback CD resolution, tick reducer effects, AutoFight rect dependencies, SkillCdText overlay plan, and injectable tick executor for overlay, frame-cache, party-sync, and auto-disable side effects; desktop capture/input/OCR/overlay adapters remain pending.",
    },
    TaskCatalogEntry {
        key: "MapMask",
        display_name: "Map Mask",
        kind: TaskKind::RealtimeTrigger,
        legacy_type: "BetterGenshinImpact.GameTask.MapMask.MapMaskTrigger",
        legacy_reference: "BetterGenshinImpact/GameTask/MapMask/MapMaskTrigger.cs",
        config_section: Some("mapMaskConfig"),
        hotkey_fields: &["mapMaskEnabledHotkey"],
        asset_roots: &[
            "GameTask/MapMask/Assets",
            "GameTask/QuickTeleport/Assets",
            "GameTask/Common/Element/Assets",
            "Assets/Map",
            "User/AutoPathing",
        ],
        launch_policy: TaskLaunchPolicy::RealtimeTick,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models MapMask config, Unknown UI trigger metadata, shared BigMap SIFT recognition metadata, BigMap stability constants, minimap ROI/matching constants, Teyvat geometry, point provider, tick/viewport decisions, overlay plan, and injectable tick executor for worker queues, overlay clears, minimap viewport clears, and big-map UI state; desktop OpenCV/SIFT, point API/cache, WPF mask overlay, and route recording adapters remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoGeniusInvokation",
        display_name: "Auto Genius Invokation",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoGeniusInvokation.AutoGeniusInvokationTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoGeniusInvokation",
        config_section: Some("autoGeniusInvokationConfig"),
        hotkey_fields: &["autoGeniusInvokationHotkey"],
        asset_roots: &[
            "GameTask/AutoGeniusInvokation/Assets",
            "User/AutoGeniusInvokation",
        ],
        launch_policy: TaskLaunchPolicy::SoloTask,
        requires_main_ui_wait: Some(false),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models AutoGeniusInvokation config, strategy source resolution, strategy script parsing, character/action plans, card/dice/template/OCR/click/wait rules, skip-main-UI launch semantics, legacy exception boundaries, and an injectable duel executor/report surface for startup, dice, action, wait, exception, cancellation, and cleanup flows; the desktop generic independent live route now returns an explicit capture/OCR/template/card-recognition/input/duel-state/strategy/reward/notification adapter gap instead of silently declining execution, while real TCG live adapters remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoWood",
        display_name: "Auto Wood",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoWood.AutoWoodTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoWood",
        config_section: Some("autoWoodConfig"),
        hotkey_fields: &["autoWoodHotkey"],
        asset_roots: &["GameTask/AutoWood/Assets"],
        launch_policy: TaskLaunchPolicy::SoloTask,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models AutoWood config, task parameter normalization, AutoWood assets/ROIs, Wangshu gadget probe, wood-count OCR parsing rules, Wonderland/legacy refresh plans, Bilibili login gate, loop phases, and an injectable executor for startup, refresh, OCR count, cutting, cancellation, and cleanup; desktop live capture, template matching, input dispatch, WinRT wood-count OCR fallback, window/power control, Wonderland/legacy refresh adapters, Bilibili login via the Relogin platform driver, and no-op overlay cleanup for draw-disabled AutoWood locators are wired, while Paddle OCR parity and real-game regression remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoFight",
        display_name: "Auto Fight",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoFight.AutoFightTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoFight",
        config_section: Some("autoFightConfig"),
        hotkey_fields: &["autoFightHotkey", "oneKeyFightHotkey"],
        asset_roots: &["GameTask/AutoFight/Assets", "User/AutoFight"],
        launch_policy: TaskLaunchPolicy::SoloTask,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Combat strategy paths, script parser, command/round model, script/configured-team alias normalization, team-context script selection, command filtering, team metadata, ActionSchedulerByCd runtime skip planning, command execution planning, static input expansion, known-team input playback, fight-loop decision planning, finish-detection input/pixel probe planning, and independent-task preparation are ported; the guarded desktop generic independent live route can now run the AutoFight finish-detection probe with mode=finishProbe while reporting full fight-loop completion as false; visual team recognition and full native fight loop execution are pending.",
    },
    TaskCatalogEntry {
        key: "AutoOpenChest",
        display_name: "Auto Open Chest",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoOpenChest.AutoOpenChestTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoOpenChest",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["GameTask/AutoOpenChest/Assets"],
        launch_policy: TaskLaunchPolicy::SoloTask,
        requires_main_ui_wait: Some(false),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models AutoOpenChest locators, 60-second search-loop policy, forward/backward/camera/interact/flower actions, per-frame decision reporting, and a desktop live executor for capture/template matching/input dispatch/cancellation/logging/flower handling; legacy draw-disabled locator overlay cleanup is a no-op, while TaskContext/SystemControl preflight and real-game regression remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoDomain",
        display_name: "Auto Domain",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoDomain.AutoDomainTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoDomain",
        config_section: Some("autoDomainConfig"),
        hotkey_fields: &["autoDomainHotkey"],
        asset_roots: &[
            "GameTask/AutoDomain/Assets",
            "GameTask/AutoFight/Assets",
            "GameTask/Common/Element/Assets",
            "GameTask/AutoPick/Assets",
            "User/AutoFight",
        ],
        launch_policy: TaskLaunchPolicy::SoloTask,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models AutoDomain config/params, domain entry retries, Sunday reward selection, combat/tree/reward/resin/artifact-salvage phases, template locators, stop/retry rules, and an injectable executor for entry, fight, reward, resin, artifact-salvage handoff, cancellation, and cleanup; the desktop generic independent live route now returns an explicit capture/map-teleport/OCR/template/input/CombatScenes/YOLO/reward/artifact-salvage adapter gap instead of silently declining execution, while real desktop adapters remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoTrack",
        display_name: "自动追踪",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoSkip.AutoTrackTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoSkip/AutoTrackTask.cs",
        config_section: Some("autoSkipConfig"),
        hotkey_fields: &["autoTrackHotkey"],
        asset_roots: &[
            "GameTask/AutoSkip/Assets",
            "GameTask/Common/Element/Assets",
            "GameTask/QuickTeleport/Assets",
        ],
        launch_policy: TaskLaunchPolicy::SoloTask,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models AutoTrack semaphore/window startup, main-UI Paimon check, mission-text OCR distance parsing, long-distance quest-menu teleport selection, blue-track-point steering, arrival OCR, cleanup, required AutoSkip/Common/QuickTeleport locators, and an injectable executor for teleport/quest/steering/forward-release actions; desktop live phase 1 now wires BitBlt capture, PureRust template matching, WinRT mission-distance OCR, SendInput action dispatch, and no-op overlay cleanup, while legacy teleport candidate ranking parity, real overlay cleanup, non-1080p asset fallback validation, and real-game regression remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoTrackPath",
        display_name: "Auto Track Path",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoTrackPath.AutoTrackPathTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoTrackPath",
        config_section: Some("tpConfig"),
        hotkey_fields: &["autoTrackPathHotkey"],
        asset_roots: &[
            "GameTask/AutoTrackPath/Assets",
            "GameTask/QuickTeleport/Assets",
            "GameTask/Common/Element/Assets",
            "GameTask/Common/Map",
            "log/way",
        ],
        launch_policy: TaskLaunchPolicy::SoloTask,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models the obsolete AutoTrackPath way2.json input, TpConfig defaults, waypoint plans, teleport/minimap wait, mouse-angle calibration, point tracking, motion refresh, jump loop, semaphore, cancellation, cleanup rules, and an injectable executor with action reports; the desktop generic independent live route now returns an explicit TpTask/mini-map capture/map matching/orientation/input/overlay/cancellation adapter gap instead of silently declining execution, while real desktop adapters remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoMusicGame",
        display_name: "Auto Music Game",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoMusicGame.AutoMusicGameTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoMusicGame",
        config_section: Some("autoMusicGameConfig"),
        hotkey_fields: &["autoMusicGameHotkey"],
        asset_roots: &["GameTask/AutoMusicGame/Assets"],
        launch_policy: TaskLaunchPolicy::SoloTask,
        requires_main_ui_wait: Some(false),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models AutoMusicGame config, six-lane 1080p key sampling coordinates, 5ms Win32 pixel polling thresholds, pure key press/release lane state machine, injectable performance runtime/report with ReleaseAllKeys cleanup, resolution warnings, album difficulty selection, completion/canorus locators, skip-main-UI launch behavior, and injectable AutoAlbumTask executor flow for album page validation, completion skipping, difficulty selection, per-song performance handoff, next-song navigation, cancellation, and timing; desktop live commands and generic independent task routing now cover manual performance and album execution, including 16:9 checks, game-window metrics, Win32 GetPixel sampling, SendInput KeyDown/KeyUp, all-key cleanup, album all-songs OCR rejection, template/click IO, BtnList performance-stop handoff, and AlbumStart/AlbumEnd/AlbumError notification dispatch; generic route selects performance by default or album with mode/executionMode=album.",
    },
    TaskCatalogEntry {
        key: "AutoPathing",
        display_name: "Auto Pathing",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoPathing.PathExecutor",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoPathing",
        config_section: Some("pathingConditionConfig"),
        hotkey_fields: &["executePathHotkey", "pathRecorderHotkey", "addWaypointHotkey"],
        asset_roots: &["User/AutoPathing", "GameTask/AutoTrackPath/Assets"],
        launch_policy: TaskLaunchPolicy::SoloTask,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Route JSON model is ported with PathExecutor-style segmentation, preflight, waypoint phases, typed action plans, and a planning-only movement contract that now derives top-level pending dependencies from actual waypoint phase/action contracts; default AutoPathing planning applies the migrated Teyvat LegacyTrackMap coordinate conversion for route waypoints and non-teleport segment seeds while retaining the remaining native movement dependencies; the Rust action boundary now consumes movement contracts through an injected movement runtime, executes SetTime through the common-job live bridge, reports log_output actions, models the use_gadget not_wait QuickUseGadget action sequence while keeping cooldown-OCR gadget waits pending, models pick_around circular middle-click pickup input sequences with legacy turn parsing and timing math, models nahida_collect long-hold ElementalSkill scan sequences with legacy DPI-scaled mouse motion, key-release cleanup semantics, and PathExecutor after-action delay while keeping combat-scene avatar/CD/input dispatch pending, lets the desktop movement runtime write log_output messages to the daily desktop log at BeforeMoveToTarget, routes exit_and_relogin/WonderlandCycle actions into Relogin/WonderlandCycle common-job plans, executes HandleTeleport phases inside movement-contract consumption by handing Teleport common-job plans including force_tp intents to the caller-provided live executor, reuses those phase reports in the action boundary to avoid duplicate teleport execution, consumes Teleport navigation seeds into AutoPathing previous-position seed reports when available, and is reachable from the guarded desktop generic independent live route as an AutoPathingActionBoundary report that injects a BitBlt-backed movement runtime for healthy RecoverWhenLowHp probes and AutoEat QuickUseGadget low-HP recovery slices with follow-up HP confirmation, honors pathingConditionConfig.onlyInTeleportRecover for non-teleport waypoints, and explicitly marks completion_scope=action_boundary_only, nested movement contract consumption/native-pending phase status, and native_pathing_completed=false; PathExecutor party healing, revive modal OCR/clicking, Statue of the Seven recovery, navigation, suspend/resume, final navigation state writes, sequence-safe action input dispatch, combat/action handlers, and native movement execution remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoBoss",
        display_name: "Auto Boss",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoBoss.AutoBossTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoBoss",
        config_section: Some("autoBossConfig"),
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/AutoBoss/Assets",
            "GameTask/AutoFight/Assets",
            "GameTask/Common/Element/Assets",
            "User/AutoFight",
        ],
        launch_policy: TaskLaunchPolicy::SoloTask,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models AutoBoss config/params, supported boss data, required route files, original/supplemental resin gates, AutoFight handoff, reward navigation/claim, revive retry, post-fight repositioning, and an injectable executor for route/combat/reward/cancellation/cleanup outcomes; the desktop generic independent live route now returns an explicit capture/OCR/template/pathing/key-mouse/CombatScenes/reward/notification/cancellation adapter gap instead of silently declining execution, while real desktop adapters remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoLeyLineOutcrop",
        display_name: "自动地脉花",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoLeyLineOutcrop.AutoLeyLineOutcropTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoLeyLineOutcrop",
        config_section: Some("autoLeyLineOutcropConfig"),
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/AutoLeyLineOutcrop/Assets",
            "GameTask/AutoFight/Assets",
            "GameTask/AutoPick/Assets",
            "GameTask/Common/Element/Assets",
            "User/AutoFight",
        ],
        launch_policy: TaskLaunchPolicy::SoloTask,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models AutoLeyLineOutcrop config/params, static country and node route data, handbook/manual-map discovery semantics, BFS path selection, target/rerun route derivation, AutoFight handoff, OCR finish rules, resin exhaustion/recheck, reward resin priority, friendship-team switching, post-reward drop scan, custom-mark overlay cleanup, and an injectable executor for route/fight/reward/rerun/cancellation flows; the desktop generic independent live route now returns an explicit capture/OCR/template/TpTask/PathExecutor/key-mouse/CombatScenes/ScanPickTask/mask-overlay/notification adapter gap instead of silently declining execution, while real desktop adapters remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoStygianOnslaught",
        display_name: "Auto Stygian Onslaught",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoStygianOnslaught.AutoStygianOnslaughtTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoStygianOnslaught",
        config_section: Some("autoStygianOnslaughtConfig"),
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/AutoFight/Assets",
            "GameTask/Common/Element/Assets",
            "GameTask/QuickTeleport/Assets",
            "GameTask/AutoPick/Assets",
            "User/AutoFight",
        ],
        launch_policy: TaskLaunchPolicy::SoloTask,
        requires_main_ui_wait: Some(false),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models AutoStygianOnslaught config/defaults, combat script path selection, Stygian finite-state graph, event-menu navigation, teleport/domain entrance detection, hard-mode selection, fixed boss coordinates, in-page preset-team switching, Stygian combat loop boundaries, domain-end OCR rule, leyline flower interaction, resin usage semantics, exit-domain flow, quick-only AutoArtifactSalvage handoff, and an injectable executor/report surface for navigation, combat, reward, exit, artifact salvage, cancellation, and cleanup flows; the desktop generic independent live route now returns an explicit capture/OCR/template/combat-command/input/reward/resin/artifact-salvage/notification adapter gap instead of silently declining execution, while real desktop adapters remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoFishing",
        display_name: "Auto Fishing Task",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoFishing.AutoFishingTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoFishing/AutoFishingTask.cs",
        config_section: Some("autoFishingConfig"),
        hotkey_fields: &["autoFishingGameHotkey"],
        asset_roots: &["GameTask/AutoFishing/Assets"],
        launch_policy: TaskLaunchPolicy::ScriptDispatcher,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models the script-dispatched AutoFishing task config, enabled gate, time policy rounds, tick-loop control decisions, BehaviorTree stages, pure Blackboard reset/state contract, fish/bait/RodNet model metadata, pure find-fish timeout/viewpoint/initial-state/turn decisions, pure EnterFishingMode retry/timeout/confirm/crop/selected-bait/pitch-reset reducer, pure fishpond availability and bait selection, pure target-fish selection, pure RodNet math path, pure throw-rod initialization and adjustment decisions, pure bite/check timeout reducers, pure fish-box/pull-bar/quit reducers, startup cleanup, ordered execution plan, and an injectable full-task executor/report surface for rounds, bait, throw-rod, bite, quit, cancellation, and cleanup flows; desktop live capture, BehaviorTree execution, YOLO/GridIcon/Torch/RodNet inference, OpenCV/OCR, input dispatch, overlays, and cancellation adapters remain pending.",
    },
    TaskCatalogEntry {
        key: "AutoCook",
        display_name: "Auto Cook",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoCook.AutoCookTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoCook",
        config_section: Some("autoCookConfig"),
        hotkey_fields: &["autoCookGameHotkey"],
        asset_roots: &["GameTask/Common/Element/Assets"],
        launch_policy: TaskLaunchPolicy::ScriptDispatcher,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models AutoCook config, script-dispatcher invocation, cook UI/recover/confirm locators, exact color-count cooking bar rule, peak/drop state machine, injectable loop executor/report, and Space key action plan; desktop manual command and generic script-dispatcher live route now cover BitBlt capture, ElementAssets template matching, white-confirm click, SendInput Space, exact BGR/RGB color counting, and cancellation-aware delays; legacy desktop hotkey/dispatcher entrypoints remain to be retired.",
    },
    TaskCatalogEntry {
        key: "AutoArtifactSalvage",
        display_name: "Auto Artifact Salvage",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.AutoArtifactSalvage.AutoArtifactSalvageTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoArtifactSalvage",
        config_section: Some("autoArtifactSalvageConfig"),
        hotkey_fields: &["enhanceArtifactHotkey"],
        asset_roots: &["GameTask/AutoArtifactSalvage", "GameTask/Common/Element/Assets", "Assets/Model/Item"],
        launch_policy: TaskLaunchPolicy::HotkeyCommand,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models AutoArtifactSalvage config/default JS/legacy regex, 1-4 star inverse quick-select flow, destructive quick-salvage confirmation boundary, optional artifact-set filtering with gridIcon metadata, ArtifactSalvage grid constants, locked/selected HSV rules, artifact stat OCR ROIs/parsing rules, ClearScript Output contract, recognition-failure policy, manual-review-only five-star finish, independent-task invocation expansion, and an injectable executor for quick/five-star/filter/cleanup outcomes; the desktop generic independent live route now returns an explicit adapter gap instead of silently declining execution, while desktop live capture, OCR, OpenCV, ONNX inference, ClearScript-compatible JS, overlay, and input/click adapters remain pending.",
    },
    TaskCatalogEntry {
        key: "TurnAroundMacro",
        display_name: "Turn Around Macro",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.Macro.TurnAroundMacro",
        legacy_reference: "BetterGenshinImpact/GameTask/Macro/TurnAroundMacro.cs",
        config_section: Some("macroConfig"),
        hotkey_fields: &["turnAroundHotkey"],
        asset_roots: &[],
        launch_policy: TaskLaunchPolicy::HotkeyCommand,
        requires_main_ui_wait: Some(false),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models and can execute the TurnAroundMacro hotkey plan through injectable runtime hooks, preserving the legacy zero-to-one mouse interval rewrite, relative mouse move, and runaroundInterval wait; the desktop independent-task live route now consumes this plan through cancellable SendInput dispatch, while legacy hotkey registration retirement and real-game regression remain pending.",
    },
    TaskCatalogEntry {
        key: "QuickEnhanceArtifactMacro",
        display_name: "Quick Enhance Artifact Macro",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.Macro.QuickEnhanceArtifactMacro",
        legacy_reference: "BetterGenshinImpact/GameTask/Macro/QuickEnhanceArtifactMacro.cs",
        config_section: Some("macroConfig"),
        hotkey_fields: &["enhanceArtifactHotkey"],
        asset_roots: &[],
        launch_policy: TaskLaunchPolicy::HotkeyCommand,
        requires_main_ui_wait: Some(false),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models and can execute the QuickEnhanceArtifactMacro hotkey plan through injectable runtime hooks, preserving the initialized-context guard, fixed 1080p click sequence, enhanceWaitDelay addition, and final cursor move; the desktop independent-task live route now executes the macro through cancellable SendInput capture-point click/move dispatch with the legacy click down/up delays, while legacy WPF hotkey registration retirement and real-game regression remain pending.",
    },
    TaskCatalogEntry {
        key: "QuickBuy",
        display_name: "Quick Buy",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.QuickBuy.QuickBuyTask",
        legacy_reference: "BetterGenshinImpact/GameTask/QuickBuy/QuickBuyTask.cs",
        config_section: None,
        hotkey_fields: &["quickBuyHotkey"],
        asset_roots: &["GameTask/QuickBuy/Assets"],
        launch_policy: TaskLaunchPolicy::HotkeyCommand,
        requires_main_ui_wait: Some(false),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models and can execute the QuickBuy hotkey preflight, Serenitea Pot coin template branch, slider drag/click/wait sequences, and cleanup through injectable runtime hooks; desktop explicit command and generic independent task route now connect BitBlt capture, foreground process preflight, template matching, SendInput movement/clicks, waits, and capture-coordinate scaling; overlay cleanup is a no-op parity step because Rust QuickBuy does not draw WPF VisionContext overlays, while TaskContext initialization Toast remains pending.",
    },
    TaskCatalogEntry {
        key: "QuickSereniteaPot",
        display_name: "Quick Serenitea Pot",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.QuickSereniteaPot.QuickSereniteaPotTask",
        legacy_reference: "BetterGenshinImpact/GameTask/QuickSereniteaPot/QuickSereniteaPotTask.cs",
        config_section: None,
        hotkey_fields: &["quickSereniteaPotHotkey"],
        asset_roots: &[
            "GameTask/QuickSereniteaPot/Assets",
            "GameTask/QuickTeleport/Assets",
            "GameTask/Common/Element/Assets",
            "GameTask/AutoPick/Assets",
        ],
        launch_policy: TaskLaunchPolicy::HotkeyCommand,
        requires_main_ui_wait: Some(false),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models and can execute the QuickSereniteaPot hotkey preflight, inventory/open-bag retries, gadget tab click, Serenitea Pot icon placement, white-confirm click, main-UI/big-map recovery policy, F interaction text branch, and overlay cleanup through injectable runtime hooks; desktop explicit command and generic independent task route now connect BitBlt capture, foreground game-window preflight, template matching, Bv big-map detection, configured Genshin action input, capture coordinate clicks, WinRT OCR-backed FindF semantics, per-plan locator construction in place of the legacy asset singleton reset, and no-op overlay cleanup for the current non-drawing desktop locators, while TaskContext initialization Toast and real-game regression remain pending.",
    },
    TaskCatalogEntry {
        key: "UseRedeemCode",
        display_name: "Use Redeem Code",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.UseRedeemCode.UseRedemptionCodeTask",
        legacy_reference: "BetterGenshinImpact/GameTask/UseRedeemCode",
        config_section: Some("autoRedeemCodeConfig"),
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/UseRedeemCode/Assets",
            "GameTask/Common/Element/Assets",
        ],
        launch_policy: TaskLaunchPolicy::SoloTask,
        requires_main_ui_wait: Some(false),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Runs from feed/clipboard flow; Rust now models clipboard extraction, plain string or structured redeem-code config, the legacy BV/page/input plan, and an injectable executor with success/failure branch reporting; desktop feed/clipboard commands and generic independent task routing now connect WinRT OCR text locators, template clicks, SendInput, clipboard set/clear, and nested ReturnMainUi execution.",
    },
    TaskCatalogEntry {
        key: "GetGridIcons",
        display_name: "获取Grid界面物品图标",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.GetGridIcons.GetGridIconsTask",
        legacy_reference: "BetterGenshinImpact/GameTask/GetGridIcons",
        config_section: Some("getGridIconsConfig"),
        hotkey_fields: &[],
        asset_roots: &["GameTask/Common/Element/Assets", "Assets/Model/Item"],
        launch_policy: TaskLaunchPolicy::HotkeyCommand,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust models GetGridIcons config, gridName string/numeric compatibility, inventory/manual-open policy, GridScreen and ArtifactSetFilter grid constants, item-name OCR crop, ArtifactSetFilter flower-name double-OCR selection and icon-crop planning, optional star suffix color-contour rule, timestamped output directory, duplicate filename skip, PNG save behavior, related GridIconsAccuracyTest model metadata, independent-task invocation expansion, and an injectable executor for open/scan/save/cleanup reports; the runtime enumeration now carries scan_complete, and the desktop independent live route performs config parsing, capture preflight, output-directory creation, no-scan execution, routes ordinary inventory pages through legacy first-page de-highlight/column stitching plus current-visible-page inventory enumeration/crop caching, and routes ArtifactSetFilter through manual-open continuation, current-visible-page enumeration, WinRT flower-name double-OCR selection with legacy detail-page retry scrolling, and 60x60-to-125x125 icon crop execution with scan_complete=false protection before explicit GridScroller/ONNX adapter gaps; full GridScroller page scrolling, post-first-page anti-recycling clicks, Paddle OCR parity, ONNX-backed GridIcon classification, exact OpenCV parity, special-grid input beyond ArtifactSetFilter, and overlay cleanup remain pending.",
    },
    TaskCatalogEntry {
        key: "Shell",
        display_name: "Shell Task",
        kind: TaskKind::Independent,
        legacy_type: "BetterGenshinImpact.GameTask.Shell.ShellTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Shell",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &[],
        launch_policy: TaskLaunchPolicy::ScriptGroupStep,
        requires_main_ui_wait: Some(true),
        port_state: TaskPortState::Ported,
        notes: "Rust executes script-group and desktop independent shell commands through the platform shell, including disable, timeout, fire-and-forget, cancellation, and output capture semantics.",
    },
    TaskCatalogEntry {
        key: "ReturnMainUi",
        display_name: "Return Main UI",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.ReturnMainUiTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/ReturnMainUiTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/Common/Element/Assets",
            "GameTask/AutoSkip/Assets",
        ],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves a typed return-to-main-UI execution plan and desktop live page/click execution path.",
    },
    TaskCatalogEntry {
        key: "CountInventoryItem",
        display_name: "Count Inventory Item",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.CountInventoryItem",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/CountInventoryItem.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["GameTask/Common/Element/Assets", "Assets/Model/Item"],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the inventory tab, grid enumeration, icon classification, count OCR, weapon-ore prescroll, and single/multiple result-contract state machine through injectable hooks and invocation live bridge; desktop common-job live routing, AutoEatFood inventory execution, CountInventoryItem, and GetGridIcons ordinary inventory pages share game-window, BitBlt, capture-size, inventory open/prompt/tab handling, current-visible-page enumeration, and grid-icon crop helpers instead of collapsing inventory open, prompt, tab, GridIcon, grid, input, ONNX, OCR, and click gaps into one unsupported error; CountInventoryItem, AutoEatFood, and GetGridIcons ordinary inventory routes now share the legacy first-page de-highlight double-click/two-frame column stitching and stitched visible-page cell cache, with scan_complete=false until full GridScroller is wired, while complete GridScroller scan semantics and script return integration remain pending.",
    },
    TaskCatalogEntry {
        key: "Teleport",
        display_name: "Teleport",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.AutoTrackPath.TpTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoTrackPath/TpTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/Common/Map",
            "GameTask/Common/Element/Assets",
            "GameTask/AutoTrackPath/Assets",
            "GameTask/QuickTeleport/Assets",
        ],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Used by the Genshin script host for teleport and big-map movement helpers; Rust now preserves and executes typed teleport request state machines through injectable big-map/map-matching/click hooks and invocation live bridge. The desktop live bridge now dispatches OpenMap, verifies BigMap with PureRust templates, normalizes underground map state with QuickTeleport templates, opens the area menu and clicks the target country/independent map from WinRT OCR, loads tp.json, carries the shared Teyvat 256-layer SIFT recognition rule into desktop preflight, including keypoint/mat assets, SIFT/Flann metadata, 1/4 query downscale, 60x88 256-layer split grid, prev-rect fallback search, center Match, rect KnnMatchRect, and 256-to-2048 layer scale, carries the legacy MoveMapTo TpConfig defaults and Teyvat country-center anchors in the plan, resolves the nearest teleport point with the legacy position[2]/position[0] coordinate mapping, reads and adjusts the BigMap zoom slider with legacy 2.0/4.4 thresholds, preserves Teyvat coordinate conversion and target-window guard geometry, plans BigMap drags with the legacy mapScaleFactor/max-move/cosine-step/predicted-center math from the plan rule, runs MoveMapTo through a bounded prediction loop with legacy zoom-out/zoom-in target formulas, target-window rechecks, post-drag center update decisions, false-positive jump rejection, and C#-compatible >5 prediction-failure termination, removes duplicate MoveMapTo pre-drag actions, fails MoveMapTo when the runtime reports non-convergence, clicks the direct teleport-panel button, detects the QuickTeleport map-close/not-activated boundary, falls back to QuickTeleport candidate-panel template/OCR clicks with the legacy 500ms minimum delay plus 6x300ms teleport-button appear/disappear probing, applies point-not-activated ESC recovery with up to three coordinate-teleport attempts, polls main-UI completion, records the effective pathing navigation seed in the execution report, and can feed that seed into the AutoPathing action-boundary previous-position report when called from HandleTeleport, while non-CHS localization parity, native OpenCV/SIFT map matching for BigMap center+rect recognition, MoveMapTo native recognized-center feed/rect correction/force-jump recovery, track-coordinate conversion into live navigation state, and full PathExecutor movement consumption remain pending.",
    },
    TaskCatalogEntry {
        key: "WalkToF",
        display_name: "Walk To F",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.WalkToFTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/WalkToFTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["GameTask/AutoPick/Assets"],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the walk-forward, optional sprint, F-key detection, optional press, and release execution plan through desktop live template/input adapters.",
    },
    TaskCatalogEntry {
        key: "LowerHeadThenWalkTo",
        display_name: "Lower Head Then Walk To",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.LowerHeadThenWalkToTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/LowerHeadThenWalkToTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["GameTask/Common/Element/Assets", "GameTask/AutoPick/Assets"],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the lower-head tracking, target alignment, F-key OCR-result, and cleanup state machine through injectable hooks and invocation live bridge; desktop live phase 1 wires BitBlt capture, PureRust target/F-key template matching, WinRT F-key text OCR, SendInput camera/W movement, and no-op overlay cleanup while Paddle OCR white-text cropping and real overlay drawing remain pending.",
    },
    TaskCatalogEntry {
        key: "LinneaMining",
        display_name: "Linnea Mining",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.LinneaMiningTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/LinneaMiningTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["Assets/Model/Mine"],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now exposes the LinneaMining common-job plan with legacy mines/rounds parsing, Linnea avatar requirement, BgiMine YOLO metadata, mineral clustering, target selection, aiming, scan, mining, compensation, cleanup rules, and an injectable executor/report surface; desktop live avatar switching, capture, ONNX inference, mouse input, and overlay adapters remain pending.",
    },
    TaskCatalogEntry {
        key: "ScanPickDrops",
        display_name: "Scan Pick Drops",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.ScanPickTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/ScanPickTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["Assets/Model/World"],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the post-combat YOLO drop scan, search sweep, movement thresholds, target ordering, camera reset, and cleanup state machine through injectable hooks and invocation live bridge; the desktop common-job live route now validates game-window, BitBlt, and capture-size boundaries before explicitly rejecting the missing BgiWorld ONNX YOLO and overlay adapters.",
    },
    TaskCatalogEntry {
        key: "SwitchParty",
        display_name: "Switch Party",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.SwitchPartyTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/SwitchPartyTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["GameTask/Common/Element/Assets"],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the party-switch OCR/list-scan/confirm state machine through injectable hooks, invocation live bridge, and desktop WinRT OCR/template/capture-click adapter; live OCR depends on installed Windows OCR language support.",
    },
    TaskCatalogEntry {
        key: "BlessingOfTheWelkinMoon",
        display_name: "Blessing of the Welkin Moon",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.BlessingOfTheWelkinMoonTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/BlessingOfTheWelkinMoonTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/Common/Element/Assets",
            "GameTask/GameLoading/Assets",
        ],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the Welkin Moon server-time-gated template/input claim loop directly.",
    },
    TaskCatalogEntry {
        key: "ChooseTalkOption",
        display_name: "Choose Talk Option",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.ChooseTalkOptionTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/ChooseTalkOptionTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/Common/Element/Assets",
            "GameTask/AutoSkip/Assets",
        ],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the dialogue-option selection flow through an injectable OCR/color/click/input runtime, invocation live bridge, and desktop WinRT OCR/capture-click/color adapter; live OCR still depends on installed Windows OCR language support.",
    },
    TaskCatalogEntry {
        key: "ClaimBattlePassRewards",
        display_name: "Claim Battle Pass Rewards",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.ClaimBattlePassRewardsTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/ClaimBattlePassRewardsTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["GameTask/Common/Element/Assets"],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the battle-pass two-stage claim-all state machine through injectable OCR/text-click/page/locator hooks, manual-selection dialog reporting, invocation live bridge, and desktop WinRT OCR/capture-click adapter; live OCR depends on installed Windows OCR language support.",
    },
    TaskCatalogEntry {
        key: "ClaimEncounterPointsRewards",
        display_name: "Claim Encounter Points Rewards",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.ClaimEncounterPointsRewardsTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/ClaimEncounterPointsRewardsTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["GameTask/Common/Element/Assets"],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the encounter-points OCR retry and claim-branch state machine through injectable text-recognition/click/page/locator hooks, invocation live bridge, and desktop WinRT OCR/capture-click adapter; live OCR still depends on installed Windows OCR language support.",
    },
    TaskCatalogEntry {
        key: "ClaimMailRewards",
        display_name: "Claim Mail Rewards",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.ClaimMailRewardsTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/ClaimMailRewardsTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["GameTask/Common/Element/Assets"],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the mail reward claim execution plan through desktop live menu/template/click/input adapters.",
    },
    TaskCatalogEntry {
        key: "CheckRewards",
        display_name: "Check Rewards",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.CheckRewardsTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/CheckRewardsTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["GameTask/Common/Element/Assets"],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the daily reward status OCR/open-retry and notification state machine through injectable OCR/click/notify/page/locator hooks, invocation live bridge, and desktop WinRT OCR/capture-click adapter; live OCR still depends on installed Windows OCR language support.",
    },
    TaskCatalogEntry {
        key: "OneKeyExpedition",
        display_name: "One-Key Expedition",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.AutoSkip.OneKeyExpeditionTask",
        legacy_reference: "BetterGenshinImpact/GameTask/AutoSkip/OneKeyExpeditionTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["GameTask/AutoSkip/Assets"],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now exposes the one-key expedition collect/re-dispatch/exit/cleanup state machine as an independent CommonJob with injectable template/page/input/focus/overlay runtime hooks; desktop concrete bridge remains shared with the caller-provided common-job adapter.",
    },
    TaskCatalogEntry {
        key: "GoToAdventurersGuild",
        display_name: "Go To Adventurers Guild",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.GoToAdventurersGuildTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/GoToAdventurersGuildTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/Common/Element/Assets",
            "GameTask/AutoSkip/Assets",
            "GameTask/AutoPick/Assets",
        ],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the Adventurers' Guild party switch, encounter reward, navigation, dialogue, and expedition state machine through injectable hooks and invocation live bridge; the desktop common-job route shares the BitBlt capture backend, game-window metrics, frame-source, and capture-size guard used by other live common jobs, runs condition-aware preflight that skips statically inactive party/encounter branches, recognizes existing nested common-job bridges, converts bundled PathExecutor JSON through the shared AutoPathing action boundary with legacy TrackMap conversion, and wires the GoToAdventurersGuild runtime hooks into existing nested common-job live bridges plus Catherine F-interaction and talk-option drain adapters. The pathing hook now consumes the shared movement contract, skips the common-job low-HP frame probe, can hand teleport phases to the existing Teleport live bridge, and reports the first native-pending movement phase instead of the old desktop PathExecutor adapter placeholder; full movement dispatch and later real-game OCR/expedition-click parity remain pending.",
    },
    TaskCatalogEntry {
        key: "GoToCraftingBench",
        display_name: "Go To Crafting Bench",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.GoToCraftingBenchTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/GoToCraftingBenchTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/Common/Element/Assets",
            "GameTask/AutoSkip/Assets",
            "GameTask/AutoPick/Assets",
        ],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the crafting-bench navigation, dialogue, resin-count, and condensed-resin crafting state machine through injectable hooks and invocation live bridge; the desktop common-job route converts bundled PathExecutor JSON through the shared AutoPathing action boundary with legacy TrackMap conversion, consumes the shared movement contract with the common-job low-HP frame probe skipped, can hand teleport phases to the existing Teleport live bridge, wires the F-interaction retry, talk-option drain, resin-count OCR, and condensed-resin reduce/increase/confirm click adapters, and reads selected User/OneDragon config with legacy fallback to inject MinResinToKeep when scripts do not pass it explicitly. Full movement dispatch and real-game crafting-bench OCR/click regression remain pending instead of claiming completion.",
    },
    TaskCatalogEntry {
        key: "GoToSereniteaPot",
        display_name: "Go To Serenitea Pot",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.GoToSereniteaPotTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/GoToSereniteaPotTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/Common/Element/Assets",
            "GameTask/QuickTeleport/Assets",
            "GameTask/QuickSereniteaPot/Assets",
            "GameTask/AutoSkip/Assets",
            "GameTask/AutoPick/Assets",
            "GameTask/Common/Map",
            "User/OneDragon",
        ],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the Serenitea Pot entry, A Yuan search, reward, realm-depot purchase, finish, and cleanup state machine through injectable hooks and invocation live bridge; desktop common-job live routing now constructs a GoToSereniteaPot runtime, runs map-teleport entry through ReturnMainUi, OpenMap, area-menu OCR selection for 尘歌壶, realm-name OCR, legacy 2.5/2.3/2.1... home-icon zoom attempts, home-icon click, home-teleport/teleport-button retry, teleport-button disappearance verification, and main-UI wait, and lets bag-gadget mode consume the existing QuickSereniteaPot live bridge with strict Enter-only success mapping. The bag path now waits for main UI, verifies the Serenitea Pot finger locator, opens the map, reads the realm name through the planned WinRT OCR ROI, and best-effort toggles the map closed before marking entry success. A Yuan search now applies realm-specific adjustment actions, uses WinRT OCR candidates with ROI-offset correction for A Yuan/spirit text, mirrors the legacy mouse alignment policy, walks forward until the A Yuan F-interaction appears, and releases movement on success or failure. Reward claim now presses the A Yuan interaction, reuses the desktop ChooseTalkOption bridge for the trust option, OCRs the companion-count crop to skip zero-count love claims, handles the no-companion prompt, and clicks love/money/page-close locators. Realm-depot shop applies the legacy weekday/daily-repeat selector, ignores selector/unknown entries, reuses ChooseTalkOption for the shop option, clicks configured item locators, checks sold-out OCR, confirms max purchase, sends ESC, retries missing items, and closes the shop page. Finish now closes open pages, selects goodbye through ChooseTalkOption, clicks until main UI, and uses the desktop Teleport bridge back to Teyvat. Real-game OCR/click regression remains pending.",
    },
    TaskCatalogEntry {
        key: "Relogin",
        display_name: "Relogin",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.ExitAndReloginJob",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/ExitAndReloginJob.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &[
            "GameTask/AutoWood/Assets",
            "GameTask/Common/Element/Assets",
        ],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves and executes the Relogin retry/failure-policy state machine through template locator, input/page, game-window focus, and Bilibili third-party-login platform hooks.",
    },
    TaskCatalogEntry {
        key: "WonderlandCycle",
        display_name: "Wonderland Cycle",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.EnterAndExitWonderlandJob",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/EnterAndExitWonderlandJob.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["GameTask/Common/Element/Assets"],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves the Wonderland enter/exit execution plan and desktop live template/input execution path.",
    },
    TaskCatalogEntry {
        key: "SetTime",
        display_name: "Set Game Time",
        kind: TaskKind::System,
        legacy_type: "BetterGenshinImpact.GameTask.Common.Job.SetTimeTask",
        legacy_reference: "BetterGenshinImpact/GameTask/Common/Job/SetTimeTask.cs",
        config_section: None,
        hotkey_fields: &[],
        asset_roots: &["GameTask/Common/Element/Assets"],
        launch_policy: TaskLaunchPolicy::CommonJob,
        requires_main_ui_wait: None,
        port_state: TaskPortState::RuntimeScaffolded,
        notes: "Rust now preserves the in-game clock adjustment execution plan and desktop live dial/click execution path.",
    },
];

pub(super) fn task_catalog_entries() -> Vec<TaskCatalogEntry> {
    TASK_CATALOG.to_vec()
}
